# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2022, Solace Corporation, Nils Eckert (nils.eckert@solace.com)
# ---------------------------------------------------------------------------------------------

name: build
on:
  # for testing
  workflow_dispatch:
  # production
  schedule:
    - cron: '0 4 * * *'
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-18.04
    env:
      RELEASE_DIRECTORY: "release"
      NODE_VERSION: "16.x"

    steps:

      - name: Cancel job if user has insufficient permissions
        if: github.event_name == 'workflow_dispatch' && github.actor != 'NilsEckertSolace' && github.actor != 'ricardojosegomezulmke' && github.actor != '195858'
        uses: andymckay/cancel-action@0.2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker images
        run: |
          $RELEASE_DIRECTORY/build.sh

###
# End
