# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2022, Solace Corporation, Nils Eckert (nils.eckert@solace.com)
# ---------------------------------------------------------------------------------------------

name: release
on:
  release:
    types: [created]

jobs:

  release:
    runs-on: ubuntu-18.04
    env:
      DOCS_DIRECTORY: "docs"
      RELEASE_DIRECTORY: "release"
      NODE_VERSION: "16.x"
      PYTHON_VERSION: "3.8"

    steps:

      - name: Cancel job if user has insufficient permissions
        if: github.event_name == 'workflow_dispatch' && github.actor != 'NilsEckertSolace' && github.actor != 'ricardojosegomezulmke' && github.actor != '195858'
        uses: andymckay/cancel-action@0.2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "Install dependencies for documentation build"
        run: |
          python -m pip install --upgrade pip
          pip install -r $DOCS_DIRECTORY/devel/docs.requirements.txt

      - name: "Build documentation"
        run: |
          $DOCS_DIRECTORY/make.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish docker images to Docker Hub
        run: |
          $RELEASE_DIRECTORY/release.sh

      - name: "Publish documentation to gh-pages"
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          rsync -av $DOCS_DIRECTORY/build/html/ gh-pages/
          cd gh-pages
          git add -A
          git commit --allow-empty -F ../generated.txt
          # git push -f -u origin gh-pages
          git push -u origin gh-pages

###
# End
